# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x08products\"\x1f\n\x11GetProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\"=\n\x12GetProductResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x32Y\n\x0eProductService\x12G\n\nGetProduct\x12\x1b.products.GetProductRequest\x1a\x1c.products.GetProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPRODUCTREQUEST']._serialized_start=27
  _globals['_GETPRODUCTREQUEST']._serialized_end=58
  _globals['_GETPRODUCTRESPONSE']._serialized_start=60
  _globals['_GETPRODUCTRESPONSE']._serialized_end=121
  _globals['_PRODUCTSERVICE']._serialized_start=123
  _globals['_PRODUCTSERVICE']._serialized_end=212
# @@protoc_insertion_point(module_scope)
